#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikGreed.Linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Ozolsdbs_copy")]
	public partial class OzolsCopyDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertpusT_PolTuristiSarakst(pusT_PolTuristiSarakst instance);
    partial void UpdatepusT_PolTuristiSarakst(pusT_PolTuristiSarakst instance);
    partial void DeletepusT_PolTuristiSarakst(pusT_PolTuristiSarakst instance);
    #endregion
		
		public OzolsCopyDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Ozolsdbs_copyConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OzolsCopyDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OzolsCopyDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OzolsCopyDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OzolsCopyDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<pusT_kTuristApstakliTarif> pusT_kTuristApstakliTarifs
		{
			get
			{
				return this.GetTable<pusT_kTuristApstakliTarif>();
			}
		}
		
		public System.Data.Linq.Table<pusT_PolTuristiSarakst> pusT_PolTuristiSaraksts
		{
			get
			{
				return this.GetTable<pusT_PolTuristiSarakst>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pusT_kTuristApstakliTarif")]
	public partial class pusT_kTuristApstakliTarif
	{
		
		private int _TuristApstakli_ID;
		
		private System.Nullable<int> _TuristTeritorija_ID;
		
		private string _TuristApstakli;
		
		private decimal _Koef;
		
		private System.Nullable<System.DateTime> _Datums_No;
		
		private System.Nullable<System.DateTime> _Datums_Li;
		
		private System.Nullable<int> _TarifGroup;
		
		private string _TuristApstakli_eng;
		
		public pusT_kTuristApstakliTarif()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuristApstakli_ID", DbType="Int NOT NULL")]
		public int TuristApstakli_ID
		{
			get
			{
				return this._TuristApstakli_ID;
			}
			set
			{
				if ((this._TuristApstakli_ID != value))
				{
					this._TuristApstakli_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuristTeritorija_ID", DbType="Int")]
		public System.Nullable<int> TuristTeritorija_ID
		{
			get
			{
				return this._TuristTeritorija_ID;
			}
			set
			{
				if ((this._TuristTeritorija_ID != value))
				{
					this._TuristTeritorija_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuristApstakli", DbType="VarChar(64) NOT NULL", CanBeNull=false)]
		public string TuristApstakli
		{
			get
			{
				return this._TuristApstakli;
			}
			set
			{
				if ((this._TuristApstakli != value))
				{
					this._TuristApstakli = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Koef", DbType="Decimal(6,3) NOT NULL")]
		public decimal Koef
		{
			get
			{
				return this._Koef;
			}
			set
			{
				if ((this._Koef != value))
				{
					this._Koef = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datums_No", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Datums_No
		{
			get
			{
				return this._Datums_No;
			}
			set
			{
				if ((this._Datums_No != value))
				{
					this._Datums_No = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datums_Li", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> Datums_Li
		{
			get
			{
				return this._Datums_Li;
			}
			set
			{
				if ((this._Datums_Li != value))
				{
					this._Datums_Li = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TarifGroup", DbType="Int")]
		public System.Nullable<int> TarifGroup
		{
			get
			{
				return this._TarifGroup;
			}
			set
			{
				if ((this._TarifGroup != value))
				{
					this._TarifGroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuristApstakli_eng", DbType="VarChar(64)")]
		public string TuristApstakli_eng
		{
			get
			{
				return this._TuristApstakli_eng;
			}
			set
			{
				if ((this._TuristApstakli_eng != value))
				{
					this._TuristApstakli_eng = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pusT_PolTuristiSaraksts")]
	public partial class pusT_PolTuristiSarakst : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PolTuristiSaraksts;
		
		private int _Polises_ID;
		
		private string _Vards;
		
		private string _Uzvards;
		
		private string _PersKods;
		
		private System.Nullable<bool> _ApdrNemajs;
		
		private System.Nullable<int> _Apstaklis_ID;
		
		private System.Nullable<System.DateTime> _SpecDatumsNo;
		
		private System.Nullable<System.DateTime> _SpecDatumsLi;
		
		private System.Nullable<decimal> _Fransize;
		
		private System.Nullable<int> _PolDarbDienas;
		
		private System.Nullable<System.DateTime> _DzDatums;
		
		private bool _IsResident;
		
		private string _HomeAddress;
		
		private string _GuestAddress;
		
		private System.Nullable<bool> _IsLegal;
		
		private string _PassID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPolTuristiSarakstsChanging(int value);
    partial void OnPolTuristiSarakstsChanged();
    partial void OnPolises_IDChanging(int value);
    partial void OnPolises_IDChanged();
    partial void OnVardsChanging(string value);
    partial void OnVardsChanged();
    partial void OnUzvardsChanging(string value);
    partial void OnUzvardsChanged();
    partial void OnPersKodsChanging(string value);
    partial void OnPersKodsChanged();
    partial void OnApdrNemajsChanging(System.Nullable<bool> value);
    partial void OnApdrNemajsChanged();
    partial void OnApstaklis_IDChanging(System.Nullable<int> value);
    partial void OnApstaklis_IDChanged();
    partial void OnSpecDatumsNoChanging(System.Nullable<System.DateTime> value);
    partial void OnSpecDatumsNoChanged();
    partial void OnSpecDatumsLiChanging(System.Nullable<System.DateTime> value);
    partial void OnSpecDatumsLiChanged();
    partial void OnFransizeChanging(System.Nullable<decimal> value);
    partial void OnFransizeChanged();
    partial void OnPolDarbDienasChanging(System.Nullable<int> value);
    partial void OnPolDarbDienasChanged();
    partial void OnDzDatumsChanging(System.Nullable<System.DateTime> value);
    partial void OnDzDatumsChanged();
    partial void OnIsResidentChanging(bool value);
    partial void OnIsResidentChanged();
    partial void OnHomeAddressChanging(string value);
    partial void OnHomeAddressChanged();
    partial void OnGuestAddressChanging(string value);
    partial void OnGuestAddressChanged();
    partial void OnIsLegalChanging(System.Nullable<bool> value);
    partial void OnIsLegalChanged();
    partial void OnPassIDChanging(string value);
    partial void OnPassIDChanged();
    #endregion
		
		public pusT_PolTuristiSarakst()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolTuristiSaraksts", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PolTuristiSaraksts
		{
			get
			{
				return this._PolTuristiSaraksts;
			}
			set
			{
				if ((this._PolTuristiSaraksts != value))
				{
					this.OnPolTuristiSarakstsChanging(value);
					this.SendPropertyChanging();
					this._PolTuristiSaraksts = value;
					this.SendPropertyChanged("PolTuristiSaraksts");
					this.OnPolTuristiSarakstsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Polises_ID", DbType="Int NOT NULL")]
		public int Polises_ID
		{
			get
			{
				return this._Polises_ID;
			}
			set
			{
				if ((this._Polises_ID != value))
				{
					this.OnPolises_IDChanging(value);
					this.SendPropertyChanging();
					this._Polises_ID = value;
					this.SendPropertyChanged("Polises_ID");
					this.OnPolises_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vards", DbType="VarChar(32)")]
		public string Vards
		{
			get
			{
				return this._Vards;
			}
			set
			{
				if ((this._Vards != value))
				{
					this.OnVardsChanging(value);
					this.SendPropertyChanging();
					this._Vards = value;
					this.SendPropertyChanged("Vards");
					this.OnVardsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Uzvards", DbType="VarChar(32)")]
		public string Uzvards
		{
			get
			{
				return this._Uzvards;
			}
			set
			{
				if ((this._Uzvards != value))
				{
					this.OnUzvardsChanging(value);
					this.SendPropertyChanging();
					this._Uzvards = value;
					this.SendPropertyChanged("Uzvards");
					this.OnUzvardsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PersKods", DbType="VarChar(16)")]
		public string PersKods
		{
			get
			{
				return this._PersKods;
			}
			set
			{
				if ((this._PersKods != value))
				{
					this.OnPersKodsChanging(value);
					this.SendPropertyChanging();
					this._PersKods = value;
					this.SendPropertyChanged("PersKods");
					this.OnPersKodsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApdrNemajs", DbType="Bit")]
		public System.Nullable<bool> ApdrNemajs
		{
			get
			{
				return this._ApdrNemajs;
			}
			set
			{
				if ((this._ApdrNemajs != value))
				{
					this.OnApdrNemajsChanging(value);
					this.SendPropertyChanging();
					this._ApdrNemajs = value;
					this.SendPropertyChanged("ApdrNemajs");
					this.OnApdrNemajsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apstaklis_ID", DbType="Int")]
		public System.Nullable<int> Apstaklis_ID
		{
			get
			{
				return this._Apstaklis_ID;
			}
			set
			{
				if ((this._Apstaklis_ID != value))
				{
					this.OnApstaklis_IDChanging(value);
					this.SendPropertyChanging();
					this._Apstaklis_ID = value;
					this.SendPropertyChanged("Apstaklis_ID");
					this.OnApstaklis_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecDatumsNo", DbType="DateTime")]
		public System.Nullable<System.DateTime> SpecDatumsNo
		{
			get
			{
				return this._SpecDatumsNo;
			}
			set
			{
				if ((this._SpecDatumsNo != value))
				{
					this.OnSpecDatumsNoChanging(value);
					this.SendPropertyChanging();
					this._SpecDatumsNo = value;
					this.SendPropertyChanged("SpecDatumsNo");
					this.OnSpecDatumsNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SpecDatumsLi", DbType="DateTime")]
		public System.Nullable<System.DateTime> SpecDatumsLi
		{
			get
			{
				return this._SpecDatumsLi;
			}
			set
			{
				if ((this._SpecDatumsLi != value))
				{
					this.OnSpecDatumsLiChanging(value);
					this.SendPropertyChanging();
					this._SpecDatumsLi = value;
					this.SendPropertyChanged("SpecDatumsLi");
					this.OnSpecDatumsLiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fransize", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Fransize
		{
			get
			{
				return this._Fransize;
			}
			set
			{
				if ((this._Fransize != value))
				{
					this.OnFransizeChanging(value);
					this.SendPropertyChanging();
					this._Fransize = value;
					this.SendPropertyChanged("Fransize");
					this.OnFransizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PolDarbDienas", DbType="Int")]
		public System.Nullable<int> PolDarbDienas
		{
			get
			{
				return this._PolDarbDienas;
			}
			set
			{
				if ((this._PolDarbDienas != value))
				{
					this.OnPolDarbDienasChanging(value);
					this.SendPropertyChanging();
					this._PolDarbDienas = value;
					this.SendPropertyChanged("PolDarbDienas");
					this.OnPolDarbDienasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DzDatums", DbType="DateTime")]
		public System.Nullable<System.DateTime> DzDatums
		{
			get
			{
				return this._DzDatums;
			}
			set
			{
				if ((this._DzDatums != value))
				{
					this.OnDzDatumsChanging(value);
					this.SendPropertyChanging();
					this._DzDatums = value;
					this.SendPropertyChanged("DzDatums");
					this.OnDzDatumsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsResident", DbType="Bit NOT NULL")]
		public bool IsResident
		{
			get
			{
				return this._IsResident;
			}
			set
			{
				if ((this._IsResident != value))
				{
					this.OnIsResidentChanging(value);
					this.SendPropertyChanging();
					this._IsResident = value;
					this.SendPropertyChanged("IsResident");
					this.OnIsResidentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomeAddress", DbType="NVarChar(128)")]
		public string HomeAddress
		{
			get
			{
				return this._HomeAddress;
			}
			set
			{
				if ((this._HomeAddress != value))
				{
					this.OnHomeAddressChanging(value);
					this.SendPropertyChanging();
					this._HomeAddress = value;
					this.SendPropertyChanged("HomeAddress");
					this.OnHomeAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GuestAddress", DbType="NVarChar(128)")]
		public string GuestAddress
		{
			get
			{
				return this._GuestAddress;
			}
			set
			{
				if ((this._GuestAddress != value))
				{
					this.OnGuestAddressChanging(value);
					this.SendPropertyChanging();
					this._GuestAddress = value;
					this.SendPropertyChanged("GuestAddress");
					this.OnGuestAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsLegal", DbType="Bit")]
		public System.Nullable<bool> IsLegal
		{
			get
			{
				return this._IsLegal;
			}
			set
			{
				if ((this._IsLegal != value))
				{
					this.OnIsLegalChanging(value);
					this.SendPropertyChanging();
					this._IsLegal = value;
					this.SendPropertyChanged("IsLegal");
					this.OnIsLegalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassID", DbType="NVarChar(50)")]
		public string PassID
		{
			get
			{
				return this._PassID;
			}
			set
			{
				if ((this._PassID != value))
				{
					this.OnPassIDChanging(value);
					this.SendPropertyChanging();
					this._PassID = value;
					this.SendPropertyChanged("PassID");
					this.OnPassIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
